name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview
    
    - name: Install grcov
      run: |
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
        chmod +x ./grcov
        sudo mv ./grcov /usr/local/bin/
    
    - name: Build
      run: cargo build --verbose
      env:
        RUSTFLAGS: '-C instrument-coverage'
    
    - name: Run tests
      run: cargo test --lib --verbose
      env:
        RUSTFLAGS: '-C instrument-coverage'
        LLVM_PROFILE_FILE: 'cargo-test-%p-%m.profraw'
    
    - name: Generate coverage report
      run: |
        grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o coverage.lcov
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.lcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false